@extends('layouts.app')
@section('title', 'Manajemen Mahasiswa')

@push('styles')
<style>.err-box{background:var(--red-50);border:1px solid var(--red-100);border-radius:6px;padding:10px 14px;margin-bottom:14px;color:var(--red-600)}.account-status{font-size:11px}</style>
@endpush

@section('content')
<div class="page-header page-header-row"><div><h1>Manajemen Mahasiswa</h1><p>Kelola akun dan data dasar mahasiswa secara terpisah dari proses administrasi KP.</p></div><button type="button" class="btn btn-primary" onclick="openModal('modalTambah')">+ Tambah Mahasiswa</button></div>

@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="err-box">{{ $errors->first() }}</div>@endif

<div class="card" style="margin-bottom:16px"><div class="card-body" style="padding:14px 18px"><form method="GET" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><input type="text" name="search" class="form-control" style="width:260px" value="{{ request('search') }}" placeholder="Cari nama, NIM, atau email"><select name="angkatan" class="form-control" style="width:150px"><option value="">Semua angkatan</option>@foreach($angkatans as $angkatan)<option value="{{ $angkatan }}" @selected(request('angkatan') == $angkatan)>{{ $angkatan }}</option>@endforeach</select><select name="status" class="form-control" style="width:145px"><option value="">Semua status</option>@foreach(['proses'=>'Proses','seminar'=>'Seminar','selesai'=>'Selesai'] as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><button class="btn btn-outline btn-sm">Filter</button><a href="{{ route('admin.mahasiswa.index') }}" class="btn btn-outline btn-sm">Reset</a></form></div></div>

<div class="card"><div class="card-header"><h3>Daftar Akun Mahasiswa <span class="text-muted">({{ $mahasiswas->count() }})</span></h3></div><div class="table-wrap"><table><thead><tr><th>NIM</th><th>Nama</th><th>Email Login</th><th>Angkatan</th><th>Status KP</th><th>Akun</th><th>Aksi</th></tr></thead><tbody>@forelse($mahasiswas as $m)<tr><td><code>{{ $m->nim }}</code></td><td><strong>{{ $m->nama }}</strong><br><small class="text-muted">{{ $m->no_hp ?: '-' }}</small></td><td class="text-sm">{{ $m->user?->email ?? '-' }}</td><td>{{ $m->angkatan }}</td><td><span class="badge badge-{{ $m->status }}">{{ ucfirst($m->status) }}</span></td><td><span class="badge badge-selesai account-status">Aktif</span></td><td><div style="display:flex;gap:4px;flex-wrap:wrap"><a href="{{ route('admin.mahasiswa.show', $m) }}" class="btn btn-ghost btn-xs">Detail</a><button type="button" class="btn btn-outline btn-xs js-edit" data-id="{{ $m->id }}" data-nama='@json($m->nama)' data-email='@json($m->user?->email)' data-angkatan='@json($m->angkatan)' data-hp='@json($m->no_hp)' data-status='@json($m->status)'>Edit</button><form method="POST" action="{{ route('admin.mahasiswa.destroy', $m) }}" data-confirm="Hapus akun mahasiswa {{ $m->nama }}? Data KP yang terkait juga akan terhapus." style="display:inline">@csrf @method('DELETE')<button class="btn btn-danger btn-xs">Hapus</button></form></div></td></tr>@empty<tr><td colspan="7" style="text-align:center;padding:28px;color:var(--gray-400)">Belum ada data mahasiswa.</td></tr>@endforelse</tbody></table></div></div>

<div class="modal-bg" id="modalTambah"><div class="modal-box"><div class="modal-title">Tambah Akun Mahasiswa</div><form method="POST" action="{{ route('admin.mahasiswa.store') }}">@csrf<div class="form-group"><label class="form-label">NIM *</label><input class="form-control" name="nim" required></div><div class="form-group"><label class="form-label">Nama lengkap *</label><input class="form-control" name="nama" required></div><div class="form-grid"><div class="form-group"><label class="form-label">Angkatan *</label><input class="form-control" name="angkatan" inputmode="numeric" required></div><div class="form-group"><label class="form-label">No. HP</label><input class="form-control" name="no_hp"></div></div><div class="form-group"><label class="form-label">Email login *</label><input class="form-control" type="email" name="email" required></div><div class="form-group"><label class="form-label">Password *</label><input class="form-control" type="password" name="password" minlength="8" required></div><div class="modal-footer"><button type="button" class="btn btn-outline" onclick="closeModal('modalTambah')">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div>

<div class="modal-bg" id="modalEdit"><div class="modal-box"><div class="modal-title">Edit Akun Mahasiswa</div><form method="POST" id="formEdit">@csrf @method('PUT')<div class="form-group"><label class="form-label">Nama lengkap *</label><input class="form-control" name="nama" id="eNama" required></div><div class="form-grid"><div class="form-group"><label class="form-label">Angkatan *</label><input class="form-control" name="angkatan" id="eAngkatan" required></div><div class="form-group"><label class="form-label">No. HP</label><input class="form-control" name="no_hp" id="eHp"></div></div><div class="form-group"><label class="form-label">Email login *</label><input class="form-control" type="email" name="email" id="eEmail" required></div><div class="form-group"><label class="form-label">Status KP *</label><select class="form-control" name="status" id="eStatus"><option value="proses">Proses</option><option value="seminar">Seminar</option><option value="selesai">Selesai</option></select></div><div class="form-group"><label class="form-label">Password baru <small class="text-muted">(kosongkan bila tidak diubah)</small></label><input class="form-control" type="password" name="password" minlength="8"><input class="form-control" style="margin-top:8px" type="password" name="password_confirmation" minlength="8" placeholder="Konfirmasi password baru"></div><div class="modal-footer"><button type="button" class="btn btn-outline" onclick="closeModal('modalEdit')">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
@endsection

@push('scripts')
<script>document.querySelectorAll('.js-edit').forEach((button)=>button.addEventListener('click',()=>{const d=button.dataset;document.getElementById('formEdit').action=`{{ url('admin/mahasiswa') }}/${d.id}`;document.getElementById('eNama').value=JSON.parse(d.nama);document.getElementById('eEmail').value=JSON.parse(d.email);document.getElementById('eAngkatan').value=JSON.parse(d.angkatan);document.getElementById('eHp').value=JSON.parse(d.hp);document.getElementById('eStatus').value=JSON.parse(d.status);openModal('modalEdit')}));@if($errors->any())window.addEventListener('load',()=>openModal('modalTambah'));@endif</script>
@endpush
